/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatePresence: typeof import('motion-v')['AnimatePresence']
    Await: typeof import('./src/components/await.vue')['default']
    Children: typeof import('./src/components/comment/children.vue')['default']
    ComicCard: typeof import('./src/components/comic/comicCard.vue')['default']
    CommentRow: typeof import('./src/components/comment/commentRow.vue')['default']
    CommentSender: typeof import('./src/components/comment/commentSender.vue')['default']
    CommentView: typeof import('./src/components/comment/commentView.vue')['default']
    Content: typeof import('./src/components/content.vue')['default']
    FloatPopup: typeof import('./src/components/floatPopup.vue')['default']
    Image: typeof import('./src/components/image.vue')['default']
    List: typeof import('./src/components/list.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCollapseTransition: typeof import('naive-ui')['NCollapseTransition']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NIcon: typeof import('naive-ui')['NIcon']
    NResult: typeof import('naive-ui')['NResult']
    Popup: typeof import('./src/components/popup.vue')['default']
    PreviewUser: typeof import('./src/components/user/previewUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterTab: typeof import('./src/components/routerTab.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    Text: typeof import('./src/components/text.vue')['default']
    ToggleIcon: typeof import('./src/components/toggleIcon.vue')['default']
    UserInfo: typeof import('./src/components/user/userInfo.vue')['default']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImagePreview: typeof import('vant/es')['ImagePreview']
    VanLoading: typeof import('vant/es')['Loading']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    Var: typeof import('./src/components/var.vue')['default']
  }
}
