/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/subscribe/card.vue')['default']
    Children: typeof import('./src/components/comic/comment/children.vue')['default']
    ComicCard: typeof import('./src/components/comic/comicCard.vue')['default']
    ComicView: typeof import('./src/components/comic/comicView.vue')['default']
    Comment: typeof import('./src/components/comic/comment/comment.vue')['default']
    CommentRow: typeof import('./src/components/comic/comment/commentRow.vue')['default']
    CommentSender: typeof import('./src/components/game/commentSender.vue')['default']
    Dev: typeof import('./src/components/dev.vue')['default']
    Download: typeof import('./src/components/game/download.vue')['default']
    Eps: typeof import('./src/components/comic/info/eps.vue')['default']
    FloatPopup: typeof import('./src/components/floatPopup.vue')['default']
    GameCard: typeof import('./src/components/game/gameCard.vue')['default']
    Image: typeof import('./src/components/image.vue')['default']
    Likes: typeof import('./src/components/comic/info/likes.vue')['default']
    List: typeof import('./src/components/list.vue')['default']
    Markdown: typeof import('./src/components/markdown.vue')['default']
    Message: typeof import('./src/components/chat/message.vue')['default']
    MsgList: typeof import('./src/components/chat/msgList.vue')['default']
    Popup: typeof import('./src/components/popup.vue')['default']
    PreviewUser: typeof import('./src/components/user/previewUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SButton: typeof import('./src/components/subscribe/sButton.vue')['default']
    Search: typeof import('./src/components/search/search.vue')['default']
    SearchPop: typeof import('./src/components/search/searchPop.vue')['default']
    Sorter: typeof import('./src/components/search/sorter.vue')['default']
    Text: typeof import('./src/components/text.vue')['default']
    TopInfo: typeof import('./src/components/comic/info/topInfo.vue')['default']
    Uploader: typeof import('./src/components/comic/info/uploader.vue')['default']
    UserInfo: typeof import('./src/components/user/userInfo.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanImagePreview: typeof import('vant/es')['ImagePreview']
  }
}
